//登录
export const GET_LOGIN_USER = 'GET_LOGIN_USER'
//主页面
export const GET_SUPPLIER_LIST = 'GET_SUPPLIER_LIST'
export const SUPPLIER_LIST_ACTION = 'SUPPLIER_LIST_ACTION'

//添加
export const ADD_SUPPLIER_DATA = 'ADD_SUPPLIER_DATA'

//删除

export const DELETE_SUPPLIER_DATA = 'DELETE_SUPPLIER_DATA'
